global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using BuildingBlocks.CQRS;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Ordering.Domain.Events;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Application.Data;
global using Ordering.Application.Extensions;